# -*- coding: utf-8 -*-
"""Ex-Basico06-FOR-Monitoramento-Temperaturas-VF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/160D3osYdDKQywcgQt0XOgP9hLZZKM41P

Esse programa usa um loop for para verificar as temperaturas registradas por sensores em um armazém. O objetivo é identificar quais sensores estão acima da temperatura segura. Como exercício, faça um programa usando um arquivo para ler as temperaturas
"""

# Lista de temperaturas dos sensores em graus Celsius
temperaturas = [18, 22, 27, 25, 30, 24, 29, 31, 26, 19]
temperatura_limite = 28  # Limite seguro de temperatura em graus Celsius

# Verificando cada temperatura em relação ao limite seguro

#Loop for com enumerate:
#O loop percorre cada temperatura da lista.
#A função enumerate é usada para obter o índice do sensor (para identificá-lo) e a temperatura registrada.
#Esse tipo de verificação é útil para monitoramento em tempo real, permitindo identificar pontos
#críticos em um armazém e agir rapidamente caso alguma área ultrapasse a temperatura segura.

for i, temperatura in enumerate(temperaturas):
    if temperatura > temperatura_limite:
        print(f"Atenção! Sensor {i+1} está com temperatura de {temperatura}°C, acima do limite seguro.")
    else:
        print(f"Sensor {i+1} está com temperatura de {temperatura}°C, dentro do limite seguro.")