# -*- coding: utf-8 -*-
"""Ex-Basico05-FOR-Monitoramento-comarquivo-VF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NE_xSfG__ISYbiD5wIwYSBWIiFPSJzIL

Esse programa monitora as profundidades ao longo de uma rota e alerta se algum ponto é muito raso para a embarcação. usando arquivo excel. Crie um arquivo Excel chamado profundidades.xlsx com uma coluna chamada Profundidade que contém os valores de profundidade ao longo da rota.
"""

import pandas as pd

# Carregando os dados de profundidade a partir de um arquivo Excel
arquivo_excel = "profundidades.xlsx"
df = pd.read_excel(arquivo_excel)

# Definindo o calado da embarcação
calado_embarcacao = 8  # em metros

# Monitorando cada profundidade ao longo da rota
for profundidade in df['Profundidade']:
    if profundidade < calado_embarcacao:
        print(f"Atenção! Profundidade de {profundidade} metros é insuficiente para navegação segura.")
    else:
        print(f"Profundidade de {profundidade} metros é adequada.")