# -*- coding: utf-8 -*-
"""Ex-Basico07-FOR-Monitoramento-Temperaturas-VF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_5IzSORt_KXNyj8oSvLF7VbaL8J6fFlA

o programa salva as informações dos sensores que estão acima do limite em um arquivo de texto. Esse arquivo será útil para registrar e revisar as condições críticas detectadas pelo monitoramento.
"""

# Lista de temperaturas dos sensores em graus Celsius
temperaturas = [18, 22, 27, 25, 30, 24, 29, 31, 26, 19]
temperatura_limite = 28  # Limite seguro de temperatura em graus Celsius

# Nome do arquivo onde os sensores acima do limite serão salvos
arquivo_alerta = "sensores_acima_limite.txt"

# Abrindo o arquivo em modo de escrita
with open(arquivo_alerta, "w") as arquivo:
    for i, temperatura in enumerate(temperaturas):
        if temperatura > temperatura_limite:
            # Mensagem de alerta para o sensor acima do limite
            mensagem = f"Atenção! Sensor {i+1} está com temperatura de {temperatura}°C, acima do limite seguro.\n"
            print(mensagem.strip())  # Exibe a mensagem no console
            arquivo.write(mensagem)  # Salva a mensagem no arquivo
        else:
            print(f"Sensor {i+1} está com temperatura de {temperatura}°C, dentro do limite seguro.")

print(f"\nAs temperaturas acima do limite foram salvas no arquivo '{arquivo_alerta}'.")