# -*- coding: utf-8 -*-
"""Ex-Basico03-FOR-Carga-Maxima-VF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15WFq-3ZrVNfPuCZPbHnJ-xXxNpkrWYvE

Esse programa verificar os pesos dos conteineres e compara com a carga máxima permitida
"""

# Lista de pesos de cada contêiner em toneladas
pesos_conteineres = [8, 15, 7, 10, 12, 5, 20]
carga_maxima = 60  # carga máxima permitida em toneladas

# Inicializando a carga total
carga_total = 0

# Loop para adicionar os pesos e verificar se ultrapassa a carga máxima
for peso in pesos_conteineres:
    carga_total += peso
    if carga_total > carga_maxima:
        print("A carga máxima foi ultrapassada!")
        break
else:
    print(f"A carga total é {carga_total} toneladas, dentro do limite permitido.")