# -*- coding: utf-8 -*-
"""Ex-Basico02-FOR-Contêineres-VF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15lzgakBZN7clsfDHGZIBURfrJuMHbBKn

Esse programa conta quantos contêineres há de cada tipo de carga: perecível, perigosa e comum.
"""

# Lista de tipos de carga em cada contêiner
tipos_carga = ['perecível', 'comum', 'perigosa', 'comum', 'perecível', 'comum', 'perigosa']

# Inicializando os contadores
perecivel = 0
perigosa = 0
comum = 0

# Loop para contar os tipos de carga
for carga in tipos_carga:
    if carga == 'perecível':
        perecivel += 1
    elif carga == 'perigosa':
        perigosa += 1
    elif carga == 'comum':
        comum += 1

print(f"Contêineres perecíveis: {perecivel}")
print(f"Contêineres perigosos: {perigosa}")
print(f"Contêineres comuns: {comum}")