# -*- coding: utf-8 -*-
"""Ex-Basico01-FOR-Volume-Total-VF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KwGEPEEZaZZO1Ze2FoIJmbnnPdN96mAN

Esse programa calcula o volume total de cargas em diferentes contêineres a bordo de um navio, onde cada contêiner tem um volume específico.
"""

# Lista de volumes de cada contêiner em metros cúbicos
volumes_conteineres = [25, 40, 30, 20, 50, 35]

# Inicializando o volume total
volume_total = 0

# Loop para somar o volume de cada contêiner
for volume in volumes_conteineres:
    volume_total += volume

print(f"O volume total de cargas a bordo é: {volume_total} metros cúbicos")